# This is a basic workflow to help you get started with Actions

name: Take release cut

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      year:
        description: 'Release year (e.g. 22)'
        required: true
        type: number
      month:
        description: 'Release month (e.g. 5)'
        required: true
        type: number

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  branch_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout brand
        uses: actions/checkout@v3
        with:
          path: ./brand
          token: ${{ secrets.SPECS_TOKEN }}
          
      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
          path: ./frontend
          repository: karlw-bjss/specsavers_frontend
          token: ${{ secrets.SPECS_TOKEN }}
          
      - name: Common git config
        run: /bin/bash ./brand/.github/workflows/scripts/common_git_config.sh
        env:
          ACTOR: ${{ github.actor }}
      
      - id: getReleaseInfo
        name: Get release info
        run: /bin/bash ./brand/.github/workflows/scripts/get_release_info.sh
        env:
          RELEASE_YEAR: ${{ github.event.inputs.year }}
          RELEASE_MONTH: ${{ github.event.inputs.month }}
          RELEASE_MINOR: 0
          GITHUB_TOKEN: ${{ secrets.SPECS_TOKEN }}
          
      - name: Exit if release exists
        if: ${{ steps.getReleaseInfo.outputs.release_branch_exists == 'T' }}
        run: |
          echo "::error::Release branch exists"
          exit 1
      
      - name: Exit if beta exists
        if: ${{ steps.getReleaseInfo.outputs.current_beta != 'NONE' }}
        run: |
          echo "::error::Beta tag exists"
          exit 1
      
      - name: Do release cut
        run: /bin/bash ./brand/.github/workflows/scripts/release_cut.sh
        env:
          RELEASE_BRANCH: ${{ steps.getReleaseInfo.outputs.release_branch }}
          BETA_TAG: ${{ steps.getReleaseInfo.outputs.next_beta }}
          GITHUB_TOKEN: ${{ secrets.SPECS_TOKEN }}
          
      - name: Deploy
        run: |
          echo "::notice::Here we would trigger deployments to beta"
      
      - name: Success
        run: |
          echo "::notice::Here we would send any emails etc"
